#production DB for testing changes against live DB (heroku)
spring.datasource.url=jdbc:postgresql://c38j9kbm97l2pa.cluster-czz5s0kz4scl.eu-west-1.rds.amazonaws.com:5432/d2mlp7saiq6hmt
spring.datasource.username=u5bvnnh8lgplo2
spring.datasource.password=p307a0719abb9a387981a2b13b48b50042cc5c4c3a7d32a3964d3bf14dc9d7b74
spring.datasource.driver-class-name=org.postgresql.Driver

#for heroku - settings - config varargs
#spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PWD}
#spring.datasource.driver-class-name=org.postgresql.Driver

#local h2
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#server.port=8081

spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Vienna
spring.jpa.properties.hibernate.default_batch_fetch_size=20

#### initial run on heroku with clean DB ###
# 1. empty DB without schema - we need to create schema
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.generate-ddl=true
#spring.sql.init.mode=never

# 2. empty DB with schema - we need to execute sql init script
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.generate-ddl=true
#spring.sql.init.mode=always

# 3. everything is set-up (schema + init data)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.sql.init.mode=always
### end ###

server.require-ssl=false

#spring.jpa.show-sql=true
spring.jpa.open-in-view=false
#spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size = 10MB
spring.servlet.multipart.max-request-size = 10MB
